// import { ThemeProvider } from 'next-themes';
import { Providers } from '../components/providers';
import { ContextProvider } from '../context/Context';
import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import '../styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
        <div className="bg-white dark:bg-prim-dark">
        <Providers>
          <Navbar/>
            <main className="w-full pt-16">
              {children}
            </main>
            </Providers>
          <Footer/>
        </div>
        </ContextProvider>
      </body>
    </html>
  )
}
